import { Alert, AlertStatus, AlertSeverity, AlertType, AgencyRole } from '../types'

export class AlertService {
  /**
   * Transition alert status through the operational state machine
   */
  public static updateAlertStatus(
    alert: Alert,
    newStatus: AlertStatus,
    officer: string,
    note: string
  ): Alert {
    const updatedHistory = [
      ...alert.history,
      {
        status: newStatus,
        timestamp: new Date().toISOString(),
        updatedBy: officer,
        note
      }
    ]

    return {
      ...alert,
      status: newStatus,
      actionTaken: note,
      history: updatedHistory
    }
  }

  /**
   * Create an automated alert for a newly detected incident or suspect
   */
  public static createAlert(
    incidentId: string,
    title: string,
    severity: AlertSeverity,
    type: AlertType,
    assignedAgency: AgencyRole,
    description: string
  ): Alert {
    const now = new Date().toISOString()
    return {
      id: `ALT-${Date.now().toString().slice(-6)}`,
      incidentId,
      title,
      severity,
      type,
      status: 'NEW',
      timestamp: now,
      assignedAgency,
      description,
      history: [
        {
          status: 'NEW',
          timestamp: now,
          updatedBy: 'Automated SAGAR RAKSHAK Engine',
          note: 'Alert generated by real-time detection & correlation pipeline'
        }
      ]
    }
  }
}
